name: Compilar VS Code

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Yarn
      run: npm install -g yarn

    - name: Instalar dependencias
      run: yarn install

    - name: Compilar el proyecto
      run: yarn run compile
