name: Build VS Code desde el source

on:
  workflow_dispatch: # permite ejecutar el build manualmente
  push:
    branches: [main] # también se ejecuta en cada push a main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.1"

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependencias
        run: npm install

      - name: Compilar VS Code
        run: yarn run vscode-win32-x64

      - name: Empaquetar ejecutable
        run: |
          mkdir build-output
          copy .\.build\win32-x64\* build-output

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: vscode-build
          path: build-output/
